name: Update branch

on:
  push:
    branches:
      - 'master'
jobs:
  autoupdate:
    runs-on: ubuntu-latest
    steps:
      - name: Update PR Branch
        uses: adRise/update-pr-branch@v0.7.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: 'master'
          required_approval_count: 2
          require_passed_checks: false
          sort: 'created'
          direction: 'desc'
          require_auto_merge_enabled: true
