name: Update branch

on:
  push:
    branches:
      - main
  pull_request:

  workflow_dispatch:


permissions: read-all

jobs:
  update-branch:
   # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: lcdsmao/update-branch@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

